---
title: "What You Wish You Knew Before College!"
subtitle: ""
author: "Ghislain Nono Gueye, Ph.D."
date: ""
output:
  xaringan::moon_reader:
    css: [default, "style/style.css"]
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---

```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
```

class: center, middle

# Let's Get To Know Our Data!

---

**Load packages**

```{r, message = FALSE, warning = FALSE}
library(readr)
library(dplyr)
library(ggplot2)
```

---

**Download the data**

```{r, message = FALSE, warning = FALSE}
grads <- read_csv("data/recent_grads.csv")
grads
```

---
**Get a glimpse of the data**

```{r, eval = FALSE}
glimpse(grads)
```

---

class: center, middle

### What is the distribution of median salaries by major?

---

```{r, message = FALSE, warning = FALSE}
ggplot(data = grads, mapping = aes(x = Median)) +
	geom_histogram()
```

---

class: center, middle

### Visualize median salaries by major category?

---

```{r, message = FALSE, warning = FALSE}

salary_maj_cat <- grads %>%
	group_by(Major_category) %>%
	summarize(median_salary = median(Median))

salary_maj_cat
```

---

```{r}
ggplot(data = salary_maj_cat, mapping = aes(x = Major_category, y = median_salary)) +
	geom_col()
```

---

```{r}
library(forcats)

salary_maj_cat %>%
	mutate(Major_category = fct_reorder(Major_category, median_salary)) %>%

ggplot(mapping = aes(x = Major_category, y = median_salary)) +
	geom_col()
```

---

```{r}
salary_maj_cat <- salary_maj_cat %>%
	mutate(Major_category = fct_reorder(Major_category, median_salary))

ggplot(data = salary_maj_cat, mapping = aes(x = Major_category, y = median_salary)) +
	geom_col() +
	coord_flip()
```



---
**Visualize median salaries by major categories**

```{r}
# grads %>%
	
# ggplot(data = grads, aes())
```


---

**Distribution of Median salaries by major category**

```{r}
ggplot(data = grads, aes(x = Major_category, y = Median)) +
	geom_boxplot()
```

---

```{r}
ggplot(data = grads, aes(x = Major_category, y = Median)) +
	geom_boxplot() +
	coord_flip()
```

---

```{r}
library(forcats)

ggplot(data = grads, aes(x = fct_reorder(Major_category, Median), y = Median)) +
	geom_boxplot() +
	coord_flip()
```

---

```{r}
library(forcats)

ggplot(data = grads, aes(x = fct_reorder(Major_category, Median), y = Median)) +
	geom_boxplot() +
	coord_flip() +
	labs(x = "", y = "Median salary")
```

---

```{r}
library(forcats)
library(scales)

ggplot(data = grads, aes(x = fct_reorder(Major_category, Median), y = Median)) +
	geom_boxplot() +
	coord_flip() +
	labs(x = "", y = "Median salary") +
	scale_y_continuous(labels = dollar_format())
```